spring.application.name=expense-tracker-springboot-server
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# JWT Configuration
jwt.secret=${JWT_SECRET:finvoraSuperSecretKeyThatIsAtLeast32BytesLongForSecurity!}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# SpringDoc OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
