spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/fintel_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

logging.level.com.example.expense_tracker=INFO
logging.level.org.springframework.security=WARN
